CREATE TABLE guestmap2 (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
guestmap_id TINYINT UNSIGNED NOT NULL DEFAULT '1',
top_px SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
left_px SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
date INT UNSIGNED NOT NULL DEFAULT '0',
icon TINYINT UNSIGNED NOT NULL DEFAULT '1',
name VARCHAR(25) NOT NULL,
message VARCHAR(255) NOT NULL,
ip VARCHAR(36) NOT NULL,
PRIMARY KEY (id)
) TYPE=MyISAM;